### ISSUE TITLE
Support for CS6

### ISSUE THREAD

**Issue by Eltaurus-Lt** [isteinbrecher/latex2ai#172]
I didn't find any mention of it in the release notes, but it seems that v1.0.0 no longer works with CS6. That's rather unfortunate, considering that [CC no longer supports Type 1 fonts](https://helpx.adobe.com/in/fonts/kb/postscript-type-1-fonts-end-of-support.html) used by LaTeX. 
This means that in order to be able to embed the formuli into documents without converting them to outlines one has to revert back to CS6 and v0.0.10, which will spam the "new version is available at GitHub" message every time Illustrator opens.

**Comment by isteinbrecher** [comment]
@Eltaurus-Lt yes, with version 1.0.0 CS6 support will be dropped, I will add this to the changelog. 

May I ask why you want to embeds the LaTeX2AI items? The main advantage of LaTeX2AI is that you can reuse the items and change the LaTeX code.

**Comment by Eltaurus-Lt** [comment]
Several reasons:
1) In my experience too many instances of LaTeX2AI objects in one document make Illustrator prone to crashing. Converting to text is a way to avoid this without completely losing editing capabilities.
2) For simple equations it is much faster to change one letter with Illustrator text tool rather than recompiling an embeded TeX object.
3) When exporting to pdf this preserves editing capabilities for someone who doesn't have the plugin or Illustrator.

**Comment by Eltaurus-Lt** [comment]
> What exactly do you mean with crashing, does Illustrator just close or are there any error messages?
Yes, exactly that.

> How many LaTeX2AI labels are you talking about here?
There is no hard limit. The more of them and the longer the document is edited, the higher the chances, but I would say going above 10-15 is already quite risky. Sometimes even one is enough, most crashes happened when trying to edit an existing label, or (less frequently) when adding another. 

>Could you also post your broad machine specs?
I've just updated recently, so I am yet to see how it goes on my current setup. For the previous 2+ years I've been working with the plugin (v0.0.9 afair) in Illustrator CS6, the machine specs were win10/core i7 (5th gen) 2.9 GHz/16GB DDR.

>I will try to upload a "final" v0.0.11 release where this message can be deactivated or are deactivated by default.
That would be very much appreciated, thank you.
If you come to that, could you also make the warning about non-ascii file paths disableable as well? It keeps popping up on every Ctrl+S even when a document doesn't contain any LaTeX2AI labels, which makes the message irrelevant.
(I can open a separate issue if will help to keep track of things)

**Comment by isteinbrecher** [comment]
Illustrator crashing with around 10-15 items should definitely not be the case. If this keeps happening with the new LaTeX2AI version can you please open an issue for this?

The warning about the ASCII characters in the paths is not optional, as LaTeX2AI does not support unicode paths. However, this only affects documents with LaTeX2AI labels and should not be shown otherwise. Could you please open a separate issue for that?

I uploaded a commit 451852bc where the version check in CS6 is disabled. Also the warning message regarding the document path should be fixed (I could not test this, thus the separate issue). Can you please try if this works? I don't have CS6 installed any more so I can't try this myself. [LaTeX2AI_451852bc_release_IllustratorCS6.zip](https://github.com/user-attachments/files/17611247/LaTeX2AI_451852bc_release_IllustratorCS6.zip)

**Comment by Eltaurus-Lt** [comment]
This one seems to be working great in CS6!
No version update warnings on launch and no non-ascii warnings for documents without LaTeX2AI objects.

**Comment by isteinbrecher** [comment]
Thanks for the feedback! I will publish this in the near future. Could you open the issue on the warning message regarding the document path? (this is only fixed for CS6 now and not in the main development branch)

**Comment by isteinbrecher** [comment]
This issue can be closed with the release of `v0.0.11`.
