### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by taishi-n** [isteinbrecher/latex2ai#58]
Is this plugin compatible with macOS?
If not, do you have any plans to do it?

**Comment by stoani89** [comment]
LaTeX2AI currently only supports Windows. It should be easy to port it to MacOS, however this is currently not planed, as the developers do not use / have access to a MacOS machine with Adobe Illustrator.

**Comment by mayrmt** [comment]
@isteinbrecher any plans on supporting macOS in the near future?

**Comment by isteinbrecher** [comment]
Yes there are concrete plans to port LaTeX2AI in the near future (as usual an accurate time table is difficult at this point).

**Comment by isteinbrecher** [comment]
The time has finally come and LaTeX2AI supports macOS 🚀🍏. Please have a look at the corresponding [(pre-)release version](https://github.com/isteinbrecher/latex2ai/releases/tag/v1.0.0-rc.1).

Feedback is greatly appreciated, e.g., what does/doesn't work, installation instructions, automatic determination of `ghostscript` and `latex` paths, ... .

I will leave this issue open until the pre-release version is a release version.

Tagging all participants of this issue: @taishi-n, @mayrm, @koko35p, @dhruvdcoder, @Davtax, @stau-7001, @WhenMelancholy

**Comment by pllilin** [comment]
On MacOS, I ran into an 

> “LaTeX2AI.aip” can’t be opened because Apple cannot check it for malicious software.

 error that I was not able to resolve in the Systems Preference / Security and Privacy settings, because the plugin is not directly executable. I was able to resolve this issue by executing the following command in the terminal:
`sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Illustrator\ 2025/Plug-ins.localized`
I found the fix [here](https://www.reddit.com/r/cubase/comments/kr75qj/plugin_namevst_3_cant_be_opened_because_apple/).

**Comment by isteinbrecher** [comment]
Thanks for reporting this @pllilin . This was already brought up by other users in https://github.com/isteinbrecher/latex2ai/issues/173. With the release of _v1.0.0_ this is now also in the `main` branch.

**Comment by isteinbrecher** [comment]
With the release of _v1.0.0_ macOS is supported by LaTeX2AI and this issue can be finally closed!
